### ISSUE TITLE
Label of a cover directive not highlighted

### ISSUE THREAD

**Issue by jgancedo** [PistoletPierre/language-systemverilog#1]
When writing an assertion directive like:
`less_than_four_standing_req: assert property (cnt <= 4);`

The label is highlighted. However, when writing a cover like:
`max_requests: cover property (cnt == 4);`

the label is not.

**Comment by pistoletpierre** [comment]
Will take a look at this next week. Lots to do between now and Tuesday...

**Comment by pistoletpierre** [comment]
Try updating and giving it a go now @jgancedo

**Comment by jgancedo** [comment]
Looks great now. Thank you and sorry for the late response!

**Comment by pistoletpierre** [comment]
Out of curiosity, what syntax highlighting are you using? I tried several and didn’t see highlighted labels in any case.

**Comment by jgancedo** [comment]
I am using Atom Dark. I don't exactly remember the use-case for which it wasn't showing, because I don't have access to the file I was using at the time. What I do remember is that it broke highlighting for consecutive code too.
