### ISSUE TITLE
decreaseIndentPattern does not use \b before end-like keywords

### ISSUE THREAD

**Issue by KoenGoe** [PistoletPierre/language-systemverilog#2]
`'decreaseIndentPattern': "\\s*(end|endfunction|endcase|endmodule|endclass|endtask|endgenerate|endinterface|join|join_any|join_none|endsequence|endproperty|endgroup|endclocking|endprogram|endpackage|endconfig|endtable|endprimitive)\\b"`

also matches variable_names_ending_with_end like that one, causing an unwanted decrease in indent whenever such a variable is used.

This should probably be corrected to:
`"\\s*\\b(end|endfunction|endcase|endmodule|endclass|endtask|endgenerate|endinterface|join|join_any|join_none|endsequence|endproperty|endgroup|endclocking|endprogram|endpackage|endconfig|endtable|endprimitive)\\b"`

Note that the grammar also includes this \\b word boundary before the end-like keywords

**Comment by pistoletpierre** [comment]
That should do it. Try updating and giving it a go @KoenGoe

**Comment by KoenGoe** [comment]
Perfect, thank you!
