### ISSUE TITLE
Syntax Highlighting - Comments

### ISSUE THREAD

**Issue by lvcargnini** [PistoletPierre/language-systemverilog#7]
Could we add a particular color for syntax Highlighting, specifically comments? in a particular color?
or where can I learn how to do that? Then I'll test it and submit the change. It helps when designing hundreds of modules and you need to clean code and remove comments

**Comment by pistoletpierre** [comment]
Hi @lvcargnini, you can change the color of comments by changing/modifying the theme you're using. This package will only identify parts of text as a comment, but the color of the comment is defined by the theme you're using. Changing a theme is straight-forward enough. Modifying it is a little more time-consuming but not difficult.

For instance, I'm using the "One Dark" theme, whose source code is in this repository: https://github.com/atom/one-dark-syntax.

<img width="340" alt="image" src="https://user-images.githubusercontent.com/6157706/82739389-2dfe5600-9d0d-11ea-9a96-86b6cbbd1f88.png">

Searching for 'comment' in that repository reveals a match in styles/syntax/_base.less (screencapped above). syntax--comment references @mono-3.

Searching 'mono-3' reveals a match in 'styles/colors.less':

<img width="468" alt="image" src="https://user-images.githubusercontent.com/6157706/82739358-ff807b00-9d0c-11ea-9712-cf9bac0324bd.png">

mono-3 seems to reference @syntax-hue, which is given the value 220. So @mono-3 is assigned hsl(220, 10%, 40%);

Guessing that hsl is a kind of color description format like RGB or others, search hsl color picker on Google. One of the first ones that shows up is hslpicker.com. Plugging in 220, 10, 40, you can see that the color hslpicker shows and the color of the text in my comment seem to be the same.

<img width="666" alt="image" src="https://user-images.githubusercontent.com/6157706/82739460-ad8c2500-9d0d-11ea-912e-18f0f30ae28b.png">

<img width="549" alt="image" src="https://user-images.githubusercontent.com/6157706/82739458-a402bd00-9d0d-11ea-921a-26b7eebf8796.png">

So if you find the code that defines the theme that you're using, change the colors you wish to change, and reload Atom, you'll be off to the races.
