### ISSUE TITLE
Comment detection breaks inside module instantation without parameter list

### ISSUE THREAD

**Issue by JohanMes** [PistoletPierre/language-systemverilog#9]
Hi,

As the title says, // comments are not detected in module instantations that do NOT have a parameter list:

foo foo_instance(
  .i_bla( bla), // I am not detected
 ...

But this works:

foo #() foo_instance(
  .i_bla( bla), // I am detected
 ...

Please fix. Empty parameter lists when instantiating are not universally accepted by EDA tools.

**Comment by pistoletpierre** [comment]
Hi @JohanMes, pardon the delay. Try updating to 0.12.4 - all seems well now:

<img width="292" alt="image" src="https://user-images.githubusercontent.com/6157706/118291816-fd777500-b4a5-11eb-9237-e7ef476bbc93.png">

**Comment by pistoletpierre** [comment]
Closing, assuming no news is good news. Reopen if that's not the case.
